{{- if .Values.configFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.volumes.configMapName }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configFiles }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}